### ISSUE TITLE
Can't get uncompyle2 to work on windows 8

### ISSUE THREAD

**Issue by Morfskorf** [Mysterie/uncompyle2#26]
Uncompyle2 in scripts folder aint a .py file.
and when i run 'uncompyle2 -h' i get 

C:\Program Files (x86)\Console2>uncompile2 -h
Traceback (most recent call last):
  File "C:\Python\Python27\Scripts\uncompile2.py", line 55, in <module>
    from uncompyle2 import main
  File "C:\Python\Python27\Scripts\uncompyle2.py", line 55, in <module>
ImportError: cannot import name main

ive seen this problem on your github error page, but it was closed and marked as error 34 which inturn linked to error 37.

could i get som info on how to solve this?

**Comment by Mysterie** [comment]
Did you try: python2.7 ./scripts/uncompyle2 your/file.pyc

**Comment by howmp** [comment]
Just because command 'uncompyle2' name same with moudle uncompyle2.
Rename it ,try again.
