### ISSUE TITLE
HOW TO USE UNCOMPYLE2 WINDOWS 8.1

### ISSUE THREAD

**Issue by ghost** [Mysterie/uncompyle2#29]
WHEN I TRIED TO  UNCOMPYLE  PYC  FILE. 

IT SHOWS AN ERROR LIKE   
# Embedded file name: /storage/sdcard0/com.hipipal.qpyplus/projects/Simple Server/ServerHandler.py

Traceback (most recent call last):
  File "C:\Users\DON OMET HASAN\Downloads\omet.py", line 2, in <module>
    uncompyle2.uncompyle_file("ServerHandler.pyc")
  File "C:\Python27\lib\site-packages\uncompyle2__init__.py", line 140, in uncompyle_file
    uncompyle(version, co, outstream, showasm, showast)
  File "C:\Python27\lib\site-packages\uncompyle2__init__.py", line 125, in uncompyle
    walk.gen_source(ast, customize)
  File "C:\Python27\lib\site-packages\uncompyle2\walker.py", line 1407, in gen_source
    self.print_(self.traverse(ast, isLambda=isLambda))
  File "C:\Python27\lib\site-packages\uncompyle2\walker.py", line 535, in print_
    self.write(*data)
  File "C:\Python27\lib\site-packages\uncompyle2\walker.py", line 531, in write
    self.f.write(out)
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by Mysterie** [comment]
What version of python do you have, and what is the command you launch ?
