### ISSUE TITLE
Not able to uncompile Python 2.5 file

### ISSUE THREAD

**Issue by tetherit** [Mysterie/uncompyle2#31]
I am running uncompyle2 on Python 2.7 and I am trying to uncompile a python 2.5 file, this is what I get:

```
uncompyle2 ./test.pyo
#2015.10.07 16:12:08 BST
### Can't uncompyle ./test.pyo
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-x86_64/egg/uncompyle2/__init__.py", line 197, in main
    uncompyle_file(infile, outstream, showasm, showast, deob)
  File "build/bdist.macosx-10.10-x86_64/egg/uncompyle2/__init__.py", line 129, in uncompyle_file
    version, co = _load_module(filename)
  File "build/bdist.macosx-10.10-x86_64/egg/uncompyle2/__init__.py", line 74, in _load_module
    raise ImportError, "This is a Python %s file! Only Python 2.7 files are supported." % version
ImportError: This is a Python 2.5 file! Only Python 2.7 files are supported.
# decompiled 0 files: 0 okay, 1 failed, 0 verify failed
#2015.10.07 16:12:08 BST
```

Any ideas?

**Comment by tetherit** [comment]
Ah, my bad, I removed the uncompyle2 installed by PIP and installed the latest version from source from this git repository :)
