### ISSUE TITLE
local variable 'n' referenced before assignment

### ISSUE THREAD

**Issue by tutorial0** [Mysterie/uncompyle2#32]
Hi, i got this error when i use uncompyle2:

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/uncompyle2/**init**.py", line 203, in main
    uncompyle_file(infile, outstream, showasm, showast)
  File "/Library/Python/2.7/site-packages/uncompyle2/**init**.py", line 140, in uncompyle_file
    uncompyle(version, co, outstream, showasm, showast)
  File "/Library/Python/2.7/site-packages/uncompyle2/**init**.py", line 102, in uncompyle
    tokens, customize = scanner.disassemble(co)
  File "/Library/Python/2.7/site-packages/uncompyle2/scanner26.py", line 38, in disassemble
    self.code = array('B', co.co_code[:n])
UnboundLocalError: local variable 'n' referenced before assignment

This pyc code is written with python 2.6. Can you help fix this? Thanks

**Comment by caot** [comment]
use https://pypi.python.org/pypi/uncompyle6

**Comment by rocky** [comment]
What uncompile6 (or probably any project) will need to track this down is the 2.6 bytecode. Maybe you can set that up as a gist. And since @caot remarks, that's another interesting idea: maybe you can get a disassembly, using pycdc.

**Comment by caot** [comment]
@rocky: "uncompyle6 translates Python bytecode back into equivalent Python source code. It accepts bytecodes from Python version 2.5 to 3.4 or so and has been tested on Python running versions 2.6, 2.7, 3.3, 3.4 and 3.5." By far, uncompyle2 and uncompyle6 are the best.
